build_settings:
  ignore:
    - "vendor"
    - "tests"

test:
  php_code_sniffer:
    allowed_errors: 0
    allowed_warnings: -1
  php_cpd:
    allowed_warnings: 5
    allow_failures: true
  security_checker:
    allowed_warnings: 0